version: "3.9"

services:
  api:
    build: .
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - .:/app
    command: uvicorn app.api.main:app --host 0.0.0.0 --port 8000 --reload
    depends_on:
      - redis
      # - postgres   # раскомментировать при подключении БД

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  # postgres:
  #   image: pgvector/pgvector:pg16
  #   environment:
  #     POSTGRES_USER: pnevma
  #     POSTGRES_PASSWORD: pnevma
  #     POSTGRES_DB: slavic_core
  #   ports:
  #     - "5432:5432"
  #   volumes:
  #     - pgdata:/var/lib/postgresql/data

# volumes:
#   pgdata:
